services:
  - type: worker
    name: file-sharing-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: WASABI_ACCESS_KEY
        sync: false
      - key: WASABI_SECRET_KEY
        sync: false
      - key: WASABI_BUCKET
        value: telegram-file-bot
      - key: WASABI_REGION
        value: us-east-1
